### ISSUE TITLE
ARM64 Manylinux wheels

### ISSUE THREAD

**Issue by a-hurst** [a-hurst/pysdl2-dll#5]
As per #2, it would be nice to have manylinux ARM wheels given the popularity of devices like the RPi and the advent of systems like the Pinebook Pro.

If Cirrus CI ever gets native ARM container support adding this would be trivial, but until then it would require using QEMU in some capacity (cibuildwheel has examples on how to set this up with GitHub Actions, will need to see if that translates at all to Cirrus). Alternatively, I could just run the manylinux build script in the arm64 manylinux docker image locally via QEMU for releases but that would be a pain to maintain.

**Comment by fkorotkov** [comment]
You can do multi-arch build on Cirrus via QEMU https://cirrus-ci.org/guide/docker-builder-vm/#multi-arch-builds

This might help until we have native ARM containers as you mentioned.

**Comment by a-hurst** [comment]
That's awesome @fkorotkov, thanks for pointing me in the right direction! If I have a pre-existing ARM64 docker image I want to use (the official Python `quay.io/pypa/manylinux2014_aarch64` image in my case), would there be anything special I'd need to do to use it, or should it work seamlessly already via Docker's QEMU?

**Comment by fkorotkov** [comment]
Yeah, only `docker_builder` support QEMU for now. But we might take a look at running `arm` containers the same way as we run privileged and KVM enabled ones: via running it in a separate VM. This will affect startup time but I think it might be a good workaround until GCP has ARM instances. Please follow https://github.com/cirruslabs/cirrus-ci-docs/issues/218 for updates. I'll take a look into this in the next few days.

**Comment by a-hurst** [comment]
@fkorotkov [I managed to get it working with a little wrangling](https://cirrus-ci.com/task/6328584676573184)! It's not pretty, and it's as slow as you'd expect for emulation, but it seems to work nonetheless. Here's what I did with the .yml:

```yaml
# Build 64-bit ARM manylinux wheel
task:
  name: "Build $SDL2DLL_PLATFORM (ARM64) wheel"

  env:
    matrix:
      - SDL2DLL_PLATFORM: manylinux_2_24

  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 4G

  script:
    - docker pull quay.io/pypa/manylinux_2_24_aarch64
    - docker run --rm -e SDL2DLL_PLATFORM=manylinux_2_24 -v `pwd`:/io --platform arm64 quay.io/pypa/manylinux_2_24_aarch64 /io/manylinux.sh

  binaries_artifacts:
    path: "dist/*"
```

For whatever the environment variables aren't working (I had to sub in `manylinux_2_24` instead of `$SDL2DLL_PLATFORM` in the docker commands), but otherwise everything else is fine.

An improved API for this would be wonderful though! Maybe something along the lines of:
```yaml
  container:
    image: quay.io/pypa/$SDL2DLL_PLATFORM_aarch64
    architecture: arm64
    memory: 4G
```

or alternatively `emulation: arm64` if you want to make it explicit that the architecture is being emulated and not run natively.

Thanks again for reaching out!
